mex -O cpt_Prolongation_BAMG.cpp BAMG.cpp ProlStripe_BAMG.cpp Reduce_IntSet.cpp...
       linsol_error.cpp Apply_HouHol_Rot.cpp maxVol.cpp add_new_neighs.cpp...
       get_cond.cpp maxVol_inner.cpp backsolve.cpp heapsort.cpp...
       mk_HouHolVec.cpp check_neigh_cond.cpp move_row_front.cpp...
       CXXFLAGS="-I./include/ -std=c++11 -O2 -fopenmp -fPIC"...
       LDFLAGS="-std=c++11 -fopenmp -O2" -lblas -llapacke
