mex -O cpt_Prolongation_BAMG.cpp BAMG.cpp ProlStripe_BAMG.cpp Reduce_IntSet.cpp...
       linsol_error.cpp Apply_HouHol_Rot.cpp maxVol.cpp add_new_neighs.cpp...
       get_cond.cpp maxVol_inner.cpp backsolve.cpp heapsort.cpp...
       mk_HouHolVec.cpp check_neigh_cond.cpp move_row_front.cpp...
       -Iinclude...
       -D__restrict__="__restrict"...
       COMPFLAGS="/nologo /O2 /openmp"...
       -lmwlapack
