mex -O cpt_Prolongation_EXTI.cpp EXTI_prolongation.cpp ir_heapsort.cpp...
       ONELP_ProlStripe_EXTI.cpp...
       CFLAGS="-I./include/ -std=c++11 -O2 -fopenmp -fPIC" ...
       LDFLAGS="-std=c++11 -fopenmp -O2"
