mex -O cpt_Prolongation_EXTI.cpp EXTI_prolongation.cpp ir_heapsort.cpp...
       ONELP_ProlStripe_EXTI.cpp...
       -Iinclude...
       -D__restrict__="__restrict"...
       COMPFLAGS="/nologo /O2 /openmp"
