mex -O cpt_Prolongation_HybridClas.cpp HybridClas_prolongation.cpp ...
       ProlStripe_HybridClas.cpp ir_heapsort.cpp ...
       find_bad_FS.cpp find_dist2CC.cpp ...
       -Iinclude...
       -D__restrict__="__restrict"...
       COMPFLAGS="/nologo /O2 /openmp"
