mex NSY_rFSAI_compute.cpp Compute_nsy_rfsai.cpp KapGrad_NSY.cpp SymmetrizePattern.cpp...
        compress_nsy_fsai.cpp cpt_nsy_rfsai.cpp extract_diag.cpp gather_fullsys.cpp...
        heapsort.cpp merge_row_patt.cpp ri_sortsplit_nsy.cpp transpose.cpp DEBUG.cpp wrCSRmat.cpp...
        -Iinclude...
        -D__restrict__="__restrict"...
        COMPFLAGS="/nologo /O2 /openmp"...
        -lmwlapack -lmwblas
